{
  "formatVersion": "1.1",
  "component": {
    "group": "com.meituan.robust",
    "module": "autopatchbase",
    "version": "0.4.99",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "autopatchbase-0.4.99.jar",
          "url": "autopatchbase-0.4.99.jar",
          "size": 11056,
          "sha512": "664acace4bdfe8f78154c4c16ce8694099fc12ef87f3cbaf2ad1f7a80a7ecb7d21d6deb9046bd613c24c0f201f7d1a092d6cbbbcdff7932a53f002c246792b8f",
          "sha256": "eb27bbf6ab8400ccc854a73823a284138b8240c56f813fb6e286e748306026a6",
          "sha1": "7e7c3297b7424dd2394fc7fa3dd1b105b09fd411",
          "md5": "faf63f55acb4a7ad982f25349dad89e4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "autopatchbase-0.4.99.jar",
          "url": "autopatchbase-0.4.99.jar",
          "size": 11056,
          "sha512": "664acace4bdfe8f78154c4c16ce8694099fc12ef87f3cbaf2ad1f7a80a7ecb7d21d6deb9046bd613c24c0f201f7d1a092d6cbbbcdff7932a53f002c246792b8f",
          "sha256": "eb27bbf6ab8400ccc854a73823a284138b8240c56f813fb6e286e748306026a6",
          "sha1": "7e7c3297b7424dd2394fc7fa3dd1b105b09fd411",
          "md5": "faf63f55acb4a7ad982f25349dad89e4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "autopatchbase-0.4.99-javadoc.jar",
          "url": "autopatchbase-0.4.99-javadoc.jar",
          "size": 328344,
          "sha512": "f2e4b482d19892bbccabc4f6f99c0270e695271be76a0ab4395da021af92a3cd13b00fcd6c2eb396c031d0138407c460fa56b52759298e3de11beb495ac5ddf8",
          "sha256": "b14f686bdd38bf42ef8adf3c6a031a8f49e0994bf8d1b4114244b78fa7fa0620",
          "sha1": "e95c738b649a0311948c60d0633be6dbb52d6324",
          "md5": "c45e7bd4cff9f32943b478287987465d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "autopatchbase-0.4.99-sources.jar",
          "url": "autopatchbase-0.4.99-sources.jar",
          "size": 8018,
          "sha512": "81c034074507acc1da3d28e3d88c7ddce96eda33c7fa88cb7321b99369d8bd5ac14d7fc85964caf53a185fbfa341e9c5079b3c24a50c93e2c7f8da3f05b0323e",
          "sha256": "d88b5879836cb796ad46572affe0ae648adf5fc5442a2d475bfc83c3c68e9224",
          "sha1": "a1dae601bcf2da0f9e4ec35f10e3f3b520eb15be",
          "md5": "549328494d9b479c3739449d2bed4a98"
        }
      ]
    }
  ]
}
