{
  "formatVersion": "1.1",
  "component": {
    "group": "com.meituan.robust",
    "module": "gradle-plugin",
    "version": "0.4.99",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gradle-plugin-0.4.99.jar",
          "url": "gradle-plugin-0.4.99.jar",
          "size": 64109,
          "sha512": "d304ea0d9396d66899f76a8b0ed7725269df2abf36664b9d883359734e996922eef4fe73ce5125edc72f3b7996620c37372c0920326584cb38aeebfa6629d6c4",
          "sha256": "381772730157f7c8b4c794b26e4304f5c8259b02db54287f8e9b089eb68065ef",
          "sha1": "73786a5662a7e44f895b13fbbda1dafa35546039",
          "md5": "f9a236a00cdf3806126dce27383b8e5f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.meituan.robust",
          "module": "autopatchbase",
          "version": {
            "requires": "0.4.99"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.30.2-GA"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "25.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.4.99.jar",
          "url": "gradle-plugin-0.4.99.jar",
          "size": 64109,
          "sha512": "d304ea0d9396d66899f76a8b0ed7725269df2abf36664b9d883359734e996922eef4fe73ce5125edc72f3b7996620c37372c0920326584cb38aeebfa6629d6c4",
          "sha256": "381772730157f7c8b4c794b26e4304f5c8259b02db54287f8e9b089eb68065ef",
          "sha1": "73786a5662a7e44f895b13fbbda1dafa35546039",
          "md5": "f9a236a00cdf3806126dce27383b8e5f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-plugin-0.4.99-javadoc.jar",
          "url": "gradle-plugin-0.4.99-javadoc.jar",
          "size": 305278,
          "sha512": "58c133ad2449afbcc966c126a8af555f8953f220cf2fee6a4bd2ca949de6a4f3be9112c0b1b3046e9b68aa0547d9bae6fa3134d59448964de70534de318f09c1",
          "sha256": "1372a9f818f3f54881e233c06f4db8bccec75b06b6a025bcc22d94d9c475c60b",
          "sha1": "b12208fc95fb006adef89566b414b8d127966bcf",
          "md5": "9c54d2dc8d147ceea5fba45663ea7115"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-plugin-0.4.99-sources.jar",
          "url": "gradle-plugin-0.4.99-sources.jar",
          "size": 21430,
          "sha512": "d42e854710e86651c6941949af80ababacc7dd31ba18e2c67bafc28ff53348e1f9b4df29f404f306e2c066fef47a4c4cd666b366d6c6b73f9bd1a44cfb9f68dd",
          "sha256": "98f8566337489008ab68c1d1cc6d32acd4a5b384bbf3c6aeec6170191f7b66a4",
          "sha1": "b4229805d51b11490fe8046a5bd32424d185e8f7",
          "md5": "0e4e28b81d99228d96bf8fdfbb32564e"
        }
      ]
    }
  ]
}
