{
  "formatVersion": "1.1",
  "component": {
    "group": "com.meituan.robust",
    "module": "auto-patch-plugin",
    "version": "0.4.99",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "auto-patch-plugin-0.4.99.jar",
          "url": "auto-patch-plugin-0.4.99.jar",
          "size": 2895141,
          "sha512": "18174c18073bb0a4d76e8039fc8b7fd1aab2c1395627d7c9f876c5a03a64365e2a6ac20a77ae9b43f780b5ecbd701958ddeae52492104bab6e23df1d909e1773",
          "sha256": "a86131fd7ebcd2466bf36c49d1f2e11a3a02c2806df941558e0063b6ab1d8a38",
          "sha1": "143c127dba41b6627ceeef8560ebce57fdc996b4",
          "md5": "f85d0e0c7ab76085134c9585b58497db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.meituan.robust",
          "module": "autopatchbase",
          "version": {
            "requires": "0.4.99"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.30.2-GA"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "25.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "auto-patch-plugin-0.4.99.jar",
          "url": "auto-patch-plugin-0.4.99.jar",
          "size": 2895141,
          "sha512": "18174c18073bb0a4d76e8039fc8b7fd1aab2c1395627d7c9f876c5a03a64365e2a6ac20a77ae9b43f780b5ecbd701958ddeae52492104bab6e23df1d909e1773",
          "sha256": "a86131fd7ebcd2466bf36c49d1f2e11a3a02c2806df941558e0063b6ab1d8a38",
          "sha1": "143c127dba41b6627ceeef8560ebce57fdc996b4",
          "md5": "f85d0e0c7ab76085134c9585b58497db"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "auto-patch-plugin-0.4.99-javadoc.jar",
          "url": "auto-patch-plugin-0.4.99-javadoc.jar",
          "size": 313684,
          "sha512": "b314b5d236150a1584783106e3496d08a5485651af77438dc26fb39a6d027c89302efabe98a8578c69b8db452b28417894970a514ffd780cca39874860e1187f",
          "sha256": "1cc0b55b65f71b77f4bf304f3702f733bb897e6139a80a1c8ffdd4e2e2d9d209",
          "sha1": "9f8c0f851ea080671cd00af4e90f424468f4a78d",
          "md5": "4538537feea3141d878650763bfe8ac1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "auto-patch-plugin-0.4.99-sources.jar",
          "url": "auto-patch-plugin-0.4.99-sources.jar",
          "size": 2779719,
          "sha512": "aeb844e2258e92b4c6b40dbea34a235bba278475ffd253fe29c3665c9be893b55fe5fe04cf6855cae3936dfb58b2209b4750c3f8c31030238e57d7d722ecb944",
          "sha256": "cc2a34a66ce0e07d1c785aa83a5db21d9ff381e5f359f2e22e68e8e4cbdb1e96",
          "sha1": "bcc28b882a977c13323f4282b163fa950dc4fa00",
          "md5": "2bb40a1d9b55b0e3fc3159494be851da"
        }
      ]
    }
  ]
}
